name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  easy_dart_jwt: 0.2.0
  uuid: ^4.5.1
  mysql1: ^0.20.0
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
