
How to Use the Test Driver

All automated tests can be run using the Dart/Flutter test runner. Ensure you are in the **root directory of the app** before running any of the following commands.

1. Run All Tests and Generate Coverage Report

In the terminal:

```bash
flutter test --coverage
```

This command executes all tests in the `test/` directory and generates a coverage report in `coverage/lcov.info`.


2. View Overall Coverage Summary

To view a quick summary of total test coverage:

```bash
dart tools/check_coverage.dart
```

This will output the total percentage of code covered by tests, giving a high-level view of testing completeness.



 3. View Detailed File-by-File Coverage

For a more detailed breakdown of code coverage by file:

```bash
dart tools/check_coverage_adv.dart
```

This script lists **each file along with its individual coverage percentage**, helping to identify under-tested areas of the codebase.



#### Notes:

* These scripts use the coverage data from `coverage/lcov.info`, which is generated by the `flutter test --coverage` command.
* You can customize the `tools/check_coverage.dart` scripts as needed to format output differently or set coverage thresholds.

